-- Theory chapters
import LeanMeta.C0_Orientation
import LeanMeta.C1_ExprAndName
import LeanMeta.C2_MetaM
import LeanMeta.C3_Syntax
import LeanMeta.C4_Elaboration
import LeanMeta.C5_TacticM
import LeanMeta.C6_Capstone
import LeanMeta.C7_NextSteps

-- Worked solutions (these also serve as a regression test suite)
import LeanMeta.Solutions.C0
import LeanMeta.Solutions.C1
import LeanMeta.Solutions.C2
import LeanMeta.Solutions.C3
import LeanMeta.Solutions.C4
import LeanMeta.Solutions.C5
import LeanMeta.Solutions.C6

/-!
# Lean 4 Metaprogramming for Mathematicians

AUTHORSHIP: every file in this project (all prose, code, exercises, and
solutions) was generated by Claude Opus 4.8 (Anthropic).  It builds cleanly, but
it is AI-generated material; read it critically.  See the README for details.

A from-zero tutorial on writing your own Lean 4 tactics, for people who already
formalize mathematics (`theorem … := by …`) but have never written meta-code and
assume no functional-programming background.

This root file is the **table of contents**: it imports every chapter (and the
worked solutions), so `lake build` checks the whole project.  You do not read this
file; open the chapters in `LeanMeta/` in order and step through them, watching
the Infoview.

## Reading order

* `LeanMeta/C0_Orientation.lean`: what metaprogramming is; the four monads; a
                                    from-zero primer on the functional Lean you need
* `LeanMeta/C1_ExprAndName.lean`: `Name` and `Expr`, the kernel's language
* `LeanMeta/C2_MetaM.lean`: `MetaM`; *a goal is a metavariable*
* `LeanMeta/C3_Syntax.lean`: `Syntax`, quotations, macros, hygiene
* `LeanMeta/C4_Elaboration.lean`: elaboration, `Syntax → Expr`
* `LeanMeta/C5_TacticM.lean`: writing real tactics, step by step
* `LeanMeta/C6_Capstone.lean`: `mytauto`, a backtracking propositional prover
* `LeanMeta/C7_NextSteps.lean`: debugging, cheat sheet, glossary, next steps

Each chapter `Cn` has a matching:
* `LeanMeta/Exercises/Cn.lean`: problems to solve (write your answer in the file)
* `LeanMeta/Solutions/Cn.lean`: worked, compiling answers (peek after you try)
-/
